version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/conf/nginx.apm.conf:/etc/nginx/nginx.conf
      - ./config/nginx/nginx.combined.conf:/etc/nginx/nginx.conf
  filebeat:
    container_name: filebeat
    user: root
    entrypoint: "filebeat -e -strict.perms=false"
    network_mode: host
    image: docker.elastic.co/beats/filebeat-oss:7.9.2
    volumes:
      - ./config/filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs/nginx:/var/log/nginx
      - ./logs/filebeat:/var/log/filebeat
      - filebeat:/usr/share/filebeat/data
      - /var/run/docker.sock:/var/run/docker.sock/:ro
      # This is needed for filebeat to load container log path as specified in filebeat.yml
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro

volumes:
  filebeat: